import Head from "next/head";
import Image from "next/image";
import { useId } from "react";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "../lib/query";

export default function Home() {
  const res: any = useQuery({ query: PRODUCT_QUERY });
  const { fetching, error, data } = res[0];
  const products = data?.products?.data;

  console.log(products);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Hallo Next</h1>
        {products &&
          products.map((product: any) => {
            return (
              <div key={Math.random()} style={{ maxWidth: "500px" }}>
                <h2>{product.attributes.title}</h2>
                <p>{product.attributes.description}</p>
                <Image
                  src={
                    product.attributes.image.data.attributes.formats.small.url
                  }
                  layout="fill"
                />
              </div>
            );
          })}
      </main>
    </div>
  );
}
